### ISSUE TITLE
For sarahledger 

### ISSUE THREAD

**Issue by samthevampire12** [githubteacher/maven#16]
Sup @sarahledger- what other nicknames do you go by?

**Comment by sarahledger** [comment]
Thanks for asking, Sam. I go by many names. You can also call me SLedger, Michael Sarah, Sarah LEdgar Allan Poe, or any other puns you can think of.
:heart: 

I added this to my bio as well :+1:

**Comment by sarahledger** [comment]
Hey @samthevampire12 I tried to fix it-- how is that?

**Comment by samthevampire12** [comment]
Yes, Its great! Very funny! :smile:

**Comment by LeilaSosa103** [comment]
omg your profile

**Comment by ghost** [comment]
your profile pic is so cool @samthevampire12
