### ISSUE TITLE
a question for sarahledger

### ISSUE THREAD

**Issue by WhatsupOlga** [githubteacher/maven#17]
Good afternoon @sarahledger among all what hobbies do u have?

**Comment by sarahledger** [comment]
Hey Olga :heart_eyes: I like to read, play sports, run, dance, and watch netflix

**Comment by sarahledger** [comment]
I added this to my bio as well :+1:

**Comment by sarahledger** [comment]
Hey @WhatsupOlga how do you feel about this? Better?

**Comment by WhatsupOlga** [comment]
hey @sarahledger LGTM :+1:
