### ISSUE TITLE
For samthevampire12 

### ISSUE THREAD

**Issue by Devilyn1996** [githubteacher/maven#19]
Hey @samthevampire12 - Out of all your works, which writing is your favourite?

**Comment by Devilyn1996** [comment]
Boobies

<a href="http://photobucket.com/images/trollolol" target="_blank"><img src="http://i1143.photobucket.com/albums/n625/bmacgill/Facebook/LeFaces/392237_2412458363801_1621544086_2363978_614734643_n.jpg" border="0" alt="trollolol photo: Trollolol 392237_2412458363801_1621544086_2363978_614734643_n.jpg"/></a>

**Comment by samthevampire12** [comment]
One of my favorites was, currently, is my work on wattpad called "Manga Trouble." If you want to know more about it go ahead and ask.

**Comment by samthevampire12** [comment]
@Devilyn1996 Hey, did i edit my bio enough?

**Comment by PeterBell** [comment]
LGTM :+1:
