### ISSUE TITLE
For KyleTheMagicalUnicorn

### ISSUE THREAD

**Issue by Kashie94** [githubteacher/maven#26]
Sup @KyleTheMagicalUnicorn! Do you know Mr. Krueger personally? Is Mr. Scissorhands (Edward to be exact) really his third cousin?

**Comment by TheAwesomeDan** [comment]
Da Fuq!!!!

**Comment by KyleTheMagicalUnicorn** [comment]
I've seen Nightmare on Elm Street so I guess you can say I met him,and No Mr. Scissorhands is actually Sweeny Todds long lost son and their dad is Johnny Deep

**Comment by Kashie94** [comment]
LGTM :+1:
