### ISSUE TITLE
I'm getting a laptop soon 

### ISSUE THREAD

**Issue by ghost** [githubteacher/maven#9]
So coding is something that I am definitely interested in learning more about. But I don't have a laptop at home to really do that. But I'm getting one soon so just be patient. 
- My name is Leilanny but you could call me Leila it does not matter
- I'm 15 years old and am a Gemini
- My favorite color is purple
- I have a 2 year old dog named Spike
  *I love reading books
  I could tell you a lot more stuff about myself but I can't think of anything right now so till next time! ^_^

**Comment by ghost** [comment]
I'm done. Goodbye issue... I'll miss you! ;-;

**Comment by sarahledger** [comment]
bye :broken_heart:
